# **Aljabar Linear**

In [1]:
import numpy as np

## **Scalar, Vector, Matrix**

### **Scalar**

In [4]:
S = 8
print(S)

8


### **Vector**

In [3]:
V = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
print(V.shape)
print(V)

(1, 9)
[[1 2 3 4 5 6 7 8 9]]


### **Matrix**

In [5]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(M.shape)
print(M)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### **Operation on Vector and Matrix**

##### **Addition and Subtraction on Vector**

In [6]:
V1 = np.array([[3, 5, 7]])
V2 = np.array([[2, 4, 6]])

vector_addition = V1 + V2
vector_subtraction = V1 - V2

print(vector_addition)
print(vector_subtraction)

[[ 5  9 13]]
[[1 1 1]]


##### **Addition and Subtraction on Matrix**

In [7]:
M1 = np.array([[3, 5, 7], [9, 11, 13]])
M2 = np.array([[2, 4, 6], [8, 10, 12]])

matrix_addition = M1 + M2
matrix_subtraction = M1 - M2

print(matrix_addition)
print(matrix_subtraction)

[[ 5  9 13]
 [17 21 25]]
[[1 1 1]
 [1 1 1]]


#### **Transpose on Vector and Matrix**

##### **Transpose on Vector**

In [9]:
V1 = np.array([[3, 5, 7]])
V1_transpose = np.transpose(V1)
print(V1_transpose) #convert rows to columns

[[3]
 [5]
 [7]]


In [11]:
V1_untranspose = np.transpose(V1_transpose)
print(V1_untranspose) #convert columns to rows

[[3 5 7]]


##### **Transpose on Matrix**

In [12]:
M1 = np.array([[2, 4, 6], [3, 5, 7]])
M1_transpose = np.transpose(M1)
print(M1_transpose) #convert rows to columns

[[2 3]
 [4 5]
 [6 7]]


In [13]:
M1_untranspose = np.transpose(M1_transpose)
print(M1_untranspose) #convert columns to rows

[[2 4 6]
 [3 5 7]]


#### **Multiplication and Division on Vector and Matrix**

##### **Multiplication on Vector**

In [14]:
V1 = np.array([[3, 5, 7]])
V2 = np.array([[2, 4, 6]])

vector_multiplication = V1 * V2

print(vector_multiplication)

[[ 6 20 42]]


##### **Division on Vector**

In [15]:
V1 = np.array([[3, 5, 7]])
V2 = np.array([[2, 4, 6]])

vector_division = V1 / V2

print(vector_division)

[[1.5        1.25       1.16666667]]


##### **Multiplication on Matrix**

In [17]:
M1 = np.array([[2, 4, 6], [3, 5, 7]])
M2 = np.array([[8, 10, 12], [9, 11, 13]])

matrix_multiplication = M1 * M2

print(matrix_multiplication)

[[16 40 72]
 [27 55 91]]


##### **Division on Matrix**

In [18]:
M1 = np.array([[2, 4, 6], [3, 5, 7]])
M2 = np.array([[8, 10, 12], [9, 11, 13]])

matrix_division= M1 / M2

print(matrix_division)

[[0.25       0.4        0.5       ]
 [0.33333333 0.45454545 0.53846154]]
