# **NumPy Basic**

In [1]:
import numpy as np

## **Create a Vector**

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])
b = [1, 2, 3, 4, 5, 6]

print(a)
print(b)

[1 2 3 4 5 6]
[1, 2, 3, 4, 5, 6]


In [3]:
a = a + 1
b = b + [1]

print(a)
print(b)

[2 3 4 5 6 7]
[1, 2, 3, 4, 5, 6, 1]


## **Arange vector**

In [4]:
a = np.arange(1, 10, 0.5)

print(a)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


## **Linspace Vector**

In [5]:
a = np.linspace(1, 10, 4)

print(a)

[ 1.  4.  7. 10.]


# **Array Multidimensi / Matrix**

In [6]:
a = np.array([(1, 2, 3), (4, 5, 6)])

print(a)

[[1 2 3]
 [4 5 6]]


## **Zero Matrix**

In [7]:
a = np.zeros((5, 5))

print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## **Ones Matrix**

In [8]:
a = np.ones((5, 5))

print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## **Matrix Identity**

In [9]:
a = np.identity(5)
b = np.eye(5)

print(a)
print(b)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
