In [ ]:
import numpy as np

# **Vector**

In [ ]:
a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 10]

print(a)
print(b)

[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]


In [ ]:
anp = np.array([1, 2, 3, 4, 5])
bnp = np.array([6, 7, 8, 9, 10])

print(anp)
print(bnp)

[1 2 3 4 5]
[ 6  7  8  9 10]


## **Vector Addition**

In [ ]:
add1 = a + b
add2 = anp + bnp

print(add1)
print(add2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 7  9 11 13 15]


## **Vector Subtraction**

In [ ]:
sub1 = anp - bnp

print(sub1)

[-5 -5 -5 -5 -5]


## **Vector Multiplication**

In [ ]:
multiply1 = anp * bnp

print(multiply1)

[ 6 14 24 36 50]


## **Vector Division**

In [ ]:
divide1 = anp / bnp

print(divide1)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


## **Vector Square**

In [ ]:
square1 = anp ** 2

print(square1)

[ 1  4  9 16 25]


# **Multidimensi Array NumPy (Matrix)**

In [ ]:
a = np.array(([1, 2, 3], [4, 5, 6]))
b = np.array(([7, 8, 9], [10, 11, 12]))

print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


## **Matrix Addition**

In [ ]:
matrixadd1 = a + b

print(matrixadd1)

[[ 8 10 12]
 [14 16 18]]


## **Matrix Subtraction**

In [ ]:
matrixsub1 = a - b

print(matrixsub1)

[[-6 -6 -6]
 [-6 -6 -6]]


## **Matrix Multiplication**

In [ ]:
matrixmultiply1 = a * b

print(matrixmultiply1)

[[ 7 16 27]
 [40 55 72]]


In [15]:
c = np.array(([1, 2, 3], [4, 5, 6]))
d = np.ones([3, 3])

print(c)
print(d)

[[1 2 3]
 [4 5 6]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
c_multiplty_d = np.dot(c, d)
c_multiplty_d2 = c.dot(d)

print(c_multiplty_d)
print(c_multiplty_d2)

[[ 6.  6.  6.]
 [15. 15. 15.]]
[[ 6.  6.  6.]
 [15. 15. 15.]]


## **Matrix Division**

In [ ]:
matrixdivide1 = a / b

print(matrixdivide1)

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


## **Matrix Square**

In [ ]:
matrixsquare1 = a ** 2

print(matrixsquare1)

[[ 1  4  9]
 [16 25 36]]
