In [1]:
import numpy as np

## **Horizontal Stacking Matrix**

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

aMartrix = np.zeros((2, 3))
bMatrix = np.ones((2, 3))

c = np.hstack((a, b))
d = np.hstack((aMartrix, bMatrix))

print(c)
print(d)

[1 2 3 4 5 6]
[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


## **Vertical Stacking Matrix**

In [3]:
w = np.array([1, 2, 3])
x = np.array([4, 5, 6])

wMartrix = np.zeros((3, 2))
xMatrix = np.ones((3, 2))

y = np.vstack((w, x))
z = np.vstack((wMartrix, xMatrix))

print(y)
print(z)

[[1 2 3]
 [4 5 6]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


## **Make a Matrix with Float Data Type**

In [4]:
f = np.array(([1, 2, 3], [4, 5, 6]), dtype = float)
f

array([[1., 2., 3.],
       [4., 5., 6.]])

## **Make a Matrix with Function**

In [5]:
def square(row, column):
    return row **2

def add(row, column):
    return row + column

a = np.fromfunction(square, (1, 10), dtype = float)
b = np.fromfunction(add, (4, 4), dtype = float)

print(a)
print(b)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 1. 2. 3.]
 [1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]]


## **Make a Matrix with Iteration**

In [7]:
iterable = (x * x for x in range(5))
c = np.fromiter(iterable, int)
c

array([ 0,  1,  4,  9, 16])

## **Multiple Array**

In [10]:
dtype = [('Name', 'S255'), ('Height', int)]
data = [
    ('Rizky Putra', 178),
    ('Kurniawan', 180)
]
e = np.array(data, dtype = dtype)
print(e)
print(e[0])

[(b'Rizky Putra', 178) (b'Kurniawan', 180)]
(b'Rizky Putra', 178)


## **Matrix Manipulation**

In [11]:
q = np.array(([1, 2, 3], [4, 5, 6]))
q

array([[1, 2, 3],
       [4, 5, 6]])

### **Transpose Matrix**

In [13]:
print(q.transpose(), q.shape)

[[1 4]
 [2 5]
 [3 6]] (2, 3)


### **Flatten**

In [15]:
print(q.flatten())

[1 2 3 4 5 6]


### **Resize Matrix**

In [19]:
q.resize(3, 2)
print(q, q.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2)
